### ISSUE TITLE
The module is not working, e.g. settings are not showing up.

### ISSUE THREAD

**Issue by ctbritt** [KelSolaar/fvvt-kels-utilities#1]
Nothing showing up, even when the only modules active are ItemPiles, Libwrapper, and Kel's Utilities.

**Comment by KelSolaar** [comment]
Hi @ctbritt,

I just tried on a new project, removed my coding copy, pulled the module from Foundry and it loads fine for me:

![image](https://user-images.githubusercontent.com/99779/214533229-9ed35486-7022-4f21-92e8-ba74be514036.png)

Note that ItemPiles needs `libWrapper` and `socketlib`

![image](https://user-images.githubusercontent.com/99779/214532953-367da4ca-8f19-4eac-a485-e265ec852845.png)

If you have a chance, it might be useful to open the Developer Tools and let me know if there are any errors.

Cheers,

Thomas

**Comment by ctbritt** [comment]
yeah, I have the same module set up as you, and it's just not showing up. No error messages in the console that I can see either.

**Comment by KelSolaar** [comment]
Hi,

Just to confirm, do you mean it is not listed in the module management page? Can you let me know which version of Foundry you are using and which platform so that I can try to repro?

Something you could try if you want is activating the module by setting it to `true` in the settings file of your world.

Given a world named `ramblings`, in your Foundry preferences you will find a `FoundryVTT/Data/worlds/ramblings/data/settings.db` file,

Then after the second curly brace here (note that I have many of them for some odd reason, Foundry bug?):

```json
{"key":"core.moduleConfiguration","value":"{
```

You could try to add this entry: `\"kels-utilities\":true,` as follows:

```json
{"key":"core.moduleConfiguration","value":"{\"kels-utilities\":true,
```

**Comment by ctbritt** [comment]
yeah, it's listed as enabled in the module list. But it's not showing up in the config settings panel.

**Comment by ctbritt** [comment]
just checking my settings.db, and the key combo you mentioned is in there. `kels-utilities` is set to true.

**Comment by KelSolaar** [comment]
Out of curiosity, do you see this log line:

![image](https://user-images.githubusercontent.com/99779/214763646-5a30bef5-6358-48bb-892c-534bc96e0712.png)

**Comment by KelSolaar** [comment]
I created a Windows VM on GCP to check whether Windows could be causing issues (I'm on macOS) and it was fine:

![image](https://user-images.githubusercontent.com/99779/214781886-f8406a77-6d64-4442-adc8-dcf7835fb4bb.png)

I'm really sorry it is not working for you and genuinely interested to know why!

**Comment by KelSolaar** [comment]
A FoundryVTT Discord user was suggesting to test the following possibly:

![image](https://user-images.githubusercontent.com/99779/214786567-684792c8-cd03-44aa-a366-dec964409aba.png)

**Comment by KelSolaar** [comment]
@ctbritt : FYI, I released a new version yesterday!

**Comment by Steelskinz** [comment]
Idk if it's related but I don't see the settings either, however I see this in the console : 
![image](https://user-images.githubusercontent.com/93941729/215635236-570b0578-ed83-4a3c-ac8b-dc7b7d22ef27.png)

**Comment by KelSolaar** [comment]
Oh! Great catch @Steelskinz, I will fix that tonight!

**Comment by KelSolaar** [comment]
New release is up, hopefully this should address the problem. I still have no clue why it loads, macOs and Windows are case-insensitive by default, are you guys on Linux?

**Comment by ravingdragoon** [comment]
I still receive the error after updating to the newest release.
```
Failed to load resource: the server responded with a status of 404 ()    
https://assets.forge-vtt.com/bazaar/modules/kels-utilities/0.2.2/scripts/lib/Constants.js
```

**Comment by Steelskinz** [comment]
> New release is up, hopefully this should address the problem. I still have no clue why it loads, macOs and Windows are case-insensitive by default, are you guys on Linux?

My server is running on ubuntu indeed.

**Comment by KelSolaar** [comment]
Thanks @ravingdragoon and @Steelskinz!

Sorry, I indeed missed a last import. Third time the charm?

Cheers,

Thomas

**Comment by Steelskinz** [comment]
Fixed, Third was the charm like expected !

**Comment by KelSolaar** [comment]
Awesome, thanks for your patience! :)

Closing!

**Comment by ctbritt** [comment]
Yes! It's showing up now. Yes, I was hosting on a linux cloud box, so the case of the Contents.js seems to have been what was mucking it up. 

Thanks!
